### ISSUE TITLE
POL uses 64bit Wine on a 32 bit system

### ISSUE THREAD

**Issue by Brainzyy** [PlayOnLinux/POL-POM-5#418]
I tried to install steam and this is the log I get on Ubuntu 16.04:

```
[JavaFX Application Thread] ERROR com.playonlinux.javafx.views.common.ErrorMessage - java.lang.RuntimeException: java.io.IOException: Cannot run program "/root/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wine" (in directory "/root/.PlayOnLinux-5/wineprefix/Steam/drive_c"): error=2, No such file or directory
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:27)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/root/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wine" (in directory "/root/.PlayOnLinux-5/wineprefix/Steam/drive_c"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at jdk.nashorn.internal.scripts.Script$Recompilation$75$3739AAA$\^eval\_.Wine$run(<eval>:171)
	at jdk.nashorn.internal.scripts.Script$Recompilation$74$9625A$\^eval\_.regedit$open(<eval>:349)
	at jdk.nashorn.internal.scripts.Script$Recompilation$62$167$\^eval\_.luna(<eval>:23)
	at jdk.nashorn.internal.scripts.Script$Recompilation$38$704$\^eval\_.go(<eval>:41)
	at jdk.nashorn.internal.scripts.Script$18$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	... 11 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more

Jan 02, 2017 11:10:44 PM org.springframework.context.annotation.AnnotationConfigApplicationContext doClose
INFO: Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@2ca0352a: startup date [Mon Jan 02 23:07:03 CET 2017]; root of context hierarchy
```

**Comment by plata** [comment]
Seems like you are running PoL as root. Can you try as local user?

**Comment by Brainzyy** [comment]
@plata I get this stacktrace when doing that:
`[JavaFX Application Thread] ERROR com.playonlinux.javafx.views.common.ErrorMessage - java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wine" (in directory "/home/gijs/.PlayOnLinux-5/wineprefix/Steam/drive_c"): error=2, No such file or directory
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:27)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wine" (in directory "/home/gijs/.PlayOnLinux-5/wineprefix/Steam/drive_c"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at jdk.nashorn.internal.scripts.Script$Recompilation$75$3739AAA$\^eval\_.Wine$run(<eval>:171)
	at jdk.nashorn.internal.scripts.Script$Recompilation$74$9702A$\^eval\_.regedit$open(<eval>:350)
	at jdk.nashorn.internal.scripts.Script$Recompilation$62$167$\^eval\_.luna(<eval>:23)
	at jdk.nashorn.internal.scripts.Script$Recompilation$38$704$\^eval\_.go(<eval>:41)
	at jdk.nashorn.internal.scripts.Script$18$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	... 11 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 19 more`
What I notice now is if you look at the path (/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wine), is that there are two slashes between 'engines' and 'wine' and between 'wine' and 'upstream-linux...', could that have something to do with it?

**Comment by plata** [comment]
The // shouldn't be a problem. Does the path exist on you machine?

**Comment by Brainzyy** [comment]
@plata /home/gijs/.PlayOnLinux-5/engines/wine/upstream-linux-amd64/1.8.6/bin/wine
exists.

**Comment by plata** [comment]
That's strange. I just tried again on my machine (also Ubuntu 16.04) and it worked. Maybe @qparis has an idea.

**Comment by Brainzyy** [comment]
@plata I suspect my permissions for my home folder are wrong, could that be a cause?

**Comment by plata** [comment]
Maybe. If PoL is not allowed to access wine, that will cause problems. On the other hand, the folder should have been created by PoL.

**Comment by Brainzyy** [comment]
@plata permissions are not the problem. I get the same error with all other programs as well. Any ideas @qparis ?

**Comment by Brainzyy** [comment]
Just checked on another computer also running Ubuntu 16.04 and I have the same problem.

**Comment by Brainzyy** [comment]
@plata @qparis On i386 (32bit) Ubuntu 16.04 I get a different error when trying to install something:

wine: could not exec wineserver
/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: 2: /home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: Syntax error: "(" unexpected
/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: 2: /home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: Syntax error: "(" unexpected
wine: could not exec wineserver
/home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: 2: /home/gijs/.PlayOnLinux-5/engines//wine//upstream-linux-amd64/1.8.6/bin/wineserver: Syntax error: "(" unexpected
[JavaFX Application Thread] ERROR com.playonlinux.javafx.views.common.ErrorMessage - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at jdk.internal.dynalink.beans.BeanLinker.rangeCheck(BeanLinker.java:386)
	at jdk.nashorn.internal.scripts.Script$Recompilation$89$1233$\^eval\_.WineShortcut$create(<eval>:59)
	at jdk.nashorn.internal.scripts.Script$Recompilation$38$704$\^eval\_.go(<eval>:54)
	at jdk.nashorn.internal.scripts.Script$18$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:27)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by plata** [comment]
@Brainzyy can you check what happens when you force the script to use a 32bit wine? You can do that by adding the following line to the installer script:
```javascript
.wineArchitecture("x86")
```

**Comment by Brainzyy** [comment]
@plata I get this backtrace:

[pool-2-thread-3] ERROR com.playonlinux.javafx.views.common.ErrorMessage - javax.script.ScriptException: TypeError: this._installWinePackage is not a function in <eval> at line number 330
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:27)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: <eval>:330 TypeError: this._installWinePackage is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$81$7877ADA$\^eval\_._installVersion$L:326$L:328(<eval>:330)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1615)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1618)
	at jdk.nashorn.internal.scripts.Script$Recompilation$80$7745ADA$\^eval\_._installVersion$L:326(<eval>:328)
	at jdk.nashorn.internal.objects.NativeArray$9.forEach(NativeArray.java:1615)
	at jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(IteratorAction.java:110)
	at jdk.nashorn.internal.objects.NativeArray.forEach(NativeArray.java:1618)
	at jdk.nashorn.internal.scripts.Script$Recompilation$75$7349$\^eval\_._installVersion(<eval>:326)
	at jdk.nashorn.internal.scripts.Script$Recompilation$74$3984AAA$\^eval\_.run(<eval>:173)
	at jdk.nashorn.internal.scripts.Script$Recompilation$73$10057A$\^eval\_.regedit$open(<eval>:413)
	at jdk.nashorn.internal.scripts.Script$Recompilation$63$167$\^eval\_.luna(<eval>:23)
	at jdk.nashorn.internal.scripts.Script$Recompilation$39$704$\^eval\_.go(<eval>:41)
	at jdk.nashorn.internal.scripts.Script$18$\^eval\_.:program(<eval>:3)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	... 10 more

[pool-2-thread-3] ERROR com.playonlinux.multithreading.ControlledThreadPoolExecutorService - java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-3
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Stage.<init>(Stage.java:241)
	at javafx.stage.Stage.<init>(Stage.java:227)
	at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.Dialog.<init>(Dialog.java:263)
	at javafx.scene.control.Alert.<init>(Alert.java:245)
	at javafx.scene.control.Alert.<init>(Alert.java:223)
	at com.playonlinux.javafx.views.common.ErrorMessage.<init>(ErrorMessage.java:36)
	at com.playonlinux.javafx.controller.library.LibraryController.lambda$null$7(LibraryController.java:64)
	at com.playonlinux.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:50)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:29)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "pool-2-thread-3" java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-2-thread-3
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.stage.Stage.<init>(Stage.java:241)
	at javafx.stage.Stage.<init>(Stage.java:227)
	at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
	at javafx.scene.control.Dialog.<init>(Dialog.java:263)
	at javafx.scene.control.Alert.<init>(Alert.java:245)
	at javafx.scene.control.Alert.<init>(Alert.java:223)
	at com.playonlinux.javafx.views.common.ErrorMessage.<init>(ErrorMessage.java:36)
	at com.playonlinux.javafx.controller.library.LibraryController.lambda$null$7(LibraryController.java:64)
	at com.playonlinux.scripts.nashorn.NashornEngine.handleError(NashornEngine.java:50)
	at com.playonlinux.scripts.nashorn.NashornEngine.eval(NashornEngine.java:29)
	at com.playonlinux.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:17)
	at com.playonlinux.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by plata** [comment]
@Brainzyy please use "insert code".

**Comment by Brainzyy** [comment]
@plata I'm sorry for the dumb question, but where do I find this option?

**Comment by plata** [comment]
When you write something, it's in the menu above the field you type in. You can also surround the code with "```".

**Comment by plata** [comment]
Btw: I'm also getting the error:
```
this._installWinePackage is not a function in at line number 330
```
Just didn't notice because I had wine installed already.

**Comment by Brainzyy** [comment]
@plata I'm sorry but I don't understand what you mean. I just go to "Apps" and go to development and start Notepad++ and click install. I don't see where I could put this command in.
And yes that's weird, that didn't happen before.

**Comment by plata** [comment]
@Brainzyy I was talking about the error message here in GitHub. Let me edit your message to show you what I mean.

**Comment by plata** [comment]
@Brainzyy I fixed that error. Try again.

**Comment by plata** [comment]
@qparis why did it use a 64bit wine on a 32bit Ubuntu?

**Comment by Brainzyy** [comment]
@plata First off, thank you again and sorry for my stupidity, I had no idea you were talking about GitHub.
The ".wineArchitecture("x86")" fixed it on my Ubuntu 32bit machine. It worked perfectly.
It did not fix it on my 64bit Ubuntu machine. It still spits out the IOerror with and without that line.

**Comment by Brainzyy** [comment]
@plata I changed the title to reflect the error on the 32bit system. I'll open another issue for the crash on my 64bit system. So that issues are separated.

**Comment by plata** [comment]
@Brainzyy could you check if the default architecture is determined correctly on your 32bit system (probably not)? It's fetched in Functions/Engines/Wine/script.js
```javascript
Wine.prototype.prefix = function (prefix)
```
Alternatively, you can check the playonlinux.cfg in the wineprefix.

**Comment by plata** [comment]
@Brainzyy PoL is now using 32bit wine by default. Could you check if it works for you? If so, I will close this issue.

**Comment by Brainzyy** [comment]
@plata It does not determine it correctly. In the cfg it says that my architecture is "amd64", when in reality it is "i386" (x86, 32bit).

EDIT: Alright, I'll check it out.

**Comment by Brainzyy** [comment]
@plata It works perfectly now on my 32bit Ubuntu system. It still doesn't work on my 64bit system, but I'll open another issue for that.
